from sqlalchemy import create_engine,String,Float,DateTime,Integer,Text
from sqlalchemy.orm import DeclarativeBase,Mapped,mapped_column,sessionmaker
class Base(DeclarativeBase):pass
class SignalRecord(Base):
 __tablename__='signals';id:Mapped[int]=mapped_column(Integer,primary_key=True);symbol:Mapped[str]=mapped_column(String(20),index=True);strategy:Mapped[str]=mapped_column(String(100));score:Mapped[float]=mapped_column(Float);probability:Mapped[float|None]=mapped_column(Float,nullable=True);entry_low:Mapped[float]=mapped_column(Float);entry_high:Mapped[float]=mapped_column(Float);stop_loss:Mapped[float]=mapped_column(Float);tp1:Mapped[float]=mapped_column(Float);tp2:Mapped[float]=mapped_column(Float);tp3:Mapped[float]=mapped_column(Float);rr:Mapped[float]=mapped_column(Float);data_delay_seconds:Mapped[float]=mapped_column(Float);decision:Mapped[str]=mapped_column(String(30));rejection_reason:Mapped[str|None]=mapped_column(Text,nullable=True);signal_time:Mapped[DateTime]=mapped_column(DateTime(timezone=True))
class TradeRecord(Base):
 __tablename__='trades';id:Mapped[int]=mapped_column(Integer,primary_key=True);signal_id:Mapped[int|None]=mapped_column(Integer,nullable=True);symbol:Mapped[str]=mapped_column(String(20),index=True);entry:Mapped[float]=mapped_column(Float);exit:Mapped[float|None]=mapped_column(Float,nullable=True);status:Mapped[str]=mapped_column(String(20));pnl_pct:Mapped[float]=mapped_column(Float,default=0);r_multiple:Mapped[float]=mapped_column(Float,default=0);mfe:Mapped[float]=mapped_column(Float,default=0);mae:Mapped[float]=mapped_column(Float,default=0);opened_at:Mapped[DateTime]=mapped_column(DateTime(timezone=True));closed_at:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True),nullable=True)
def make_session(url):
 args={'check_same_thread':False} if url.startswith('sqlite') else {};engine=create_engine(url,future=True,connect_args=args);Base.metadata.create_all(engine);return sessionmaker(bind=engine,expire_on_commit=False)
